// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDSF0_iujlOc5voxDZ9Z2xX7RQVDDW11w',
    appId: '1:379037253780:android:78bb7dac7a7ee58bfc7481',
    messagingSenderId: '379037253780',
    projectId: 'flutter-prep-3c03b',
    databaseURL: 'https://flutter-prep-3c03b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-3c03b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9qmGI7frwfUlM7B0WzgwC8ZVA9zJ8ujY',
    appId: '1:379037253780:ios:42853a6d0ae9e76ffc7481',
    messagingSenderId: '379037253780',
    projectId: 'flutter-prep-3c03b',
    databaseURL: 'https://flutter-prep-3c03b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-3c03b.firebasestorage.app',
    iosBundleId: 'com.example.shoppingList',
  );
}
